[WIP] StoryItem is converted to class from pure function
Doesn't work properly yet.
FIX: TypeError: this.state.storyItems.map is not a function
I assume it's due to the fact that I try to map the object literal.